/**
 * @author Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * License
 * <p>
 * Copyright 2025 Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files
 * (the "Software"), to deal in the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so,
 * subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of
 * the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package io.andreygs.jcsp.internal.processing.data.factory;

import io.andreygs.jcsp.api.processing.data.ICspDataSerializationProcessor;
import io.andreygs.jcsp.api.annotation.protocol.CspReference;
import io.andreygs.jcsp.api.annotation.protocol.CspCreateProcessor;
import io.andreygs.jcsp.api.processing.data.clazz.ICspClassSerializationProcessor;
import io.andreygs.jcsp.api.annotation.protocol.CspFixedSizeArray;
import io.andreygs.jcsp.api.exception.CspRuntimeException;
import io.andreygs.jcsp.api.protocol.CspStatus;

import java.lang.reflect.Field;
import java.lang.reflect.GenericArrayType;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 */
public class DraftCspAutoGeneratedSerializationProcessorFactory
{
    public static ICspClassSerializationProcessor createAutoGeneratedSerializationProcessor(Class<?> serializingClass)
        throws CspRuntimeException
    {
        if (!isAutoGeneratable(serializingClass))
        {
            throw CspRuntimeException.createCspRuntimeException(CspStatus.NO_SUCH_HANDLER,
                serializingClass.getName() + " is not annotated with " + CspCreateProcessor.class.getName());
        }

        List<ICspClassSerializationProcessor> callbacks = new ArrayList<ICspClassSerializationProcessor>();

        return new AutoGeneratedClassSerializationProcessor(serializingClass, callbacks);
    }

    private static boolean isAutoGeneratable(Class<?> clazz)
    {
        return clazz.isAnnotationPresent(CspCreateProcessor.class);
    }

    private static void produceCallbacks(List<ICspClassSerializationProcessor> callbacks, Class<?> clazz)
    {
        Class<?> parentClazz = clazz.getSuperclass();
        if (isAutoGeneratable(parentClazz))
        {
            callbacks.add((value, processor) -> processor.serialize(value, parentClazz));
        }

        Arrays.stream(clazz.getDeclaredFields()).forEach(field -> field.setAccessible(true));
/*
        Arrays.stream(clazz.getDeclaredFields())
            .filter(field -> field.getAnnotation(CspField.class) != null)
            .sorted(Comparator.comparingInt(field -> field.getAnnotation(CspField.class).order()))
            .forEach(field -> produceFieldSerializationCallbacks(callbacks, field));*/
    }

    private static void produceFieldSerializationCallbacks(List<ICspClassSerializationProcessor> callbacks, Field field)
    {
        Class<?> clazz = field.getType();

        if (clazz == boolean.class)
        {
            callbacks.add((value, processor) -> {
                try
                {
                    processor.serialize(field.getBoolean(value));
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }
        else if (clazz == byte.class)
        {
            callbacks.add((value, processor) -> {
                try
                {
                    processor.serializeByte(field.getByte(value));
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }
        else if (clazz == short.class)
        {
            callbacks.add((value, processor) -> {
                try
                {
                    processor.serializeShort(field.getShort(value));
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }
        else if (clazz == int.class)
        {
            callbacks.add((value, processor) -> {
                try
                {
                    processor.serializeInt(field.getInt(value));
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }
        else if (clazz == long.class)
        {
            callbacks.add((value, processor) -> {
                try
                {
                    processor.serializeLong(field.getLong(value));
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }
        else if (clazz == char.class)
        {
            callbacks.add((value, processor) -> {
                try
                {
                    processor.serializeChar(field.getChar(value));
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }
        else if (clazz == float.class)
        {
            callbacks.add((value, processor) -> {
                try
                {
                    processor.serializeFloat(field.getFloat(value));
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }
        else if (clazz == double.class)
        {
            callbacks.add((value, processor) -> {
                try
                {
                    processor.serializeDouble(field.getDouble(value));
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }

        boolean reference = field.getAnnotation(CspReference.class) != null;

        if (clazz.isArray())
        {
            boolean fixedSizeArray = field.getAnnotation(CspFixedSizeArray.class) != null;

            if (clazz == boolean[].class)
            {
                callbacks.add((value, processor) -> {
                    try
                    {
                        processor.serialize((boolean[]) field.get(value), reference, fixedSizeArray);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else if (clazz == byte[].class)
            {
                callbacks.add((value, processor) -> {
                    try
                    {
                        processor.serialize((byte[]) field.get(value), reference, fixedSizeArray);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else if (clazz == short[].class)
            {
                callbacks.add((value, processor) -> {
                    try
                    {
                        processor.serialize((short[]) field.get(value), reference, fixedSizeArray);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else if (clazz == int[].class)
            {
                callbacks.add((value, processor) -> {
                    try
                    {
                        processor.serialize((int[]) field.get(value), reference, fixedSizeArray);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else if (clazz == long[].class)
            {
                callbacks.add((value, processor) -> {
                    try
                    {
                        processor.serialize((long[]) field.get(value), reference, fixedSizeArray);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else if (clazz == char[].class)
            {
                callbacks.add((value, processor) -> {
                    try
                    {
                        processor.serialize((char[]) field.get(value), reference, fixedSizeArray);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else if (clazz == float[].class)
            {
                callbacks.add((value, processor) -> {
                    try
                    {
                        processor.serialize((float[]) field.get(value), reference, fixedSizeArray);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else if (clazz == double[].class)
            {
                callbacks.add((value, processor) -> {
                    try
                    {
                        processor.serialize((double[]) field.get(value), reference, fixedSizeArray);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else
            {
                Type type = field.getGenericType();
                if (type instanceof GenericArrayType arrayType)
                {

                }
/*
                    int elementsCount = Array.getLength(value);
                Class<?> elementsClazz = fieldClazz.getComponentType();

                if (ICspVersionable.class.isAssignableFrom(fieldClazz.getComponentType()))
                {
                    for (int i = 0; i < elementsCount; ++i)
                    {
                        Object element = Array.get(value, i);
                       // serialize((ICspVersionable) element, elementsClazz, session);
                    }
                }
                else
                {
                    for (int i = 0; i < elementsCount; ++i)
                    {
                        Object element = Array.get(value, i);
                       // serialize(element, session);
                    }
                }*/
            }
        }
        else
        {
            //serialize(field.get(value), session);
        }
    }

    private static class AutoGeneratedClassSerializationProcessor
        implements ICspClassSerializationProcessor
    {
        private final Class<?> clazz;
        private final List<ICspClassSerializationProcessor> callbacks;

        public AutoGeneratedClassSerializationProcessor(Class<?> clazz, List<ICspClassSerializationProcessor> callbacks)
        {
            this.clazz = clazz;
            this.callbacks = callbacks;
        }

        @Override
        public void serialize(Object value, ICspDataSerializationProcessor processor)
        {
            callbacks.forEach(callback -> callback.serialize(value, processor));
        }

        private ICspClassSerializationProcessor getP(Field field, Object value)
        {
            ICspClassSerializationProcessor classProcessor = (valueX, processor) -> {
                try
                {
                    processor.serializeInt(field.getInt(valueX));
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            };
            return classProcessor;
        }
    }
}
