/**
 * @author Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * License
 * <p>
 * Copyright 2025 Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files
 * (the "Software"), to deal in the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so,
 * subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of
 * the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package io.andreygs.jcsp.base.processing;

import io.andreygs.jcsp.base.processing.internal.ICspProcessor;

import java.util.Optional;

/**
 * Registrar of CSP serialization/deserialization processors for specific classes.
 * <p>
 * Registering of processor is always necessary when target class not implementing
 * {@link io.andreygs.jcsp.base.types.ICspSerializable} interface (because they are generating automatically) and not
 * instance of following types:
 * <ul>
 *     <li>any primitive: boolean, byte, short, int, long, char, float, double</li>
 *     <li>{@link String}</li>
 *     <li>{@link java.util.List}</li>
 *     <li>...to be filled next</li>
 * </ul>
 * <p>
 * But one can override autogenerated ICspSerializable subtypes processors by registering its own/.
 * <p>
 * Please note that arrays of any type must not have separate processors.
 */
public interface ICspProcessorRegistrar<T extends ICspProcessor>
{
    void registerProcessor(Class<?> clazz, T processor);
    void unregisterProcessor(Class<?> clazz);
    Optional<T> findProcessor(Class<?> clazz);
}
