/**
 * @author Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * License
 * <p>
 * Copyright 2025 Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files
 * (the "Software"), to deal in the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so,
 * subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of
 * the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package io.andreygs.jcsp.base.processing;

import java.util.Optional;

/**
 * Registrar of CSP serialization/deserialization processors for specific classes.
 * <p>
 * Registering of processor is always necessary when target class not implementing
 * {@link io.andreygs.jcsp.base.types.ICspSerializable} interface (because they are generating automatically) and not
 * instance of following types:
 * <ul>
 *     <li>any primitive: boolean, byte, short, int, long, char, float, double</li>
 *     <li>{@link String}</li>
 *     <li>{@link java.util.List}</li>
 *     <li>...to be filled next</li>
 * </ul>
 * <p>
 * But one can override autogenerated {@link io.andreygs.jcsp.base.types.ICspSerializable} subtypes processors by
 * registering its own. This approach can be handy if one wants to speed up serialization process or add some asserts
 * of deserialized (or maybe even serialized) data.
 * <p>
 * The strategy of registrars number in application is not strictly defined.
 * You can make a single one (or two, for both - serialization and deserialization) or several
 * each one for different CSP Interfaces (or modules) or/and if there are different policies
 * for work with different sources/targets of CSP interactions.
 * <p>
 * Please note that arrays of any type must not have separate processors.
 * <p>
 * Thread-safe.
 */
public interface ICspProcessorRegistrar<T extends ICspProcessor>
{
    /**
     * Registers processor for later use.
     * <p>
     * If class processor already have been registered, then new processor will override previous registration.
     * But if you want to have both processors - by one for different cases, for example -
     * you should create new registrar, fill it with all necessary processors including current one
     * and use different registrars in requisite scenarios.
     *
     * @param clazz Class that processor should handle.
     * @param processor Processor that will be used in serialization or deserialization process.
     */
    void registerProcessor(Class<?> clazz, T processor);

    /**
     * Unregisters processor for chosen class.
     *
     * @param clazz Class which processor should be unregistered.
     */
    void unregisterProcessor(Class<?> clazz);

    /**
     * Finds already registered processor for chosen class.
     *
     * @param clazz Class which processor need to be found.
     * @return optional processor value.
     */
    Optional<T> findProcessor(Class<?> clazz);
}
