/**
 * @author Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * License
 * <p>
 * Copyright 2025 Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files
 * (the "Software"), to deal in the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so,
 * subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of
 * the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package io.andreygs.jcsp.base.processing.internal;

import io.andreygs.jcsp.base.processing.ICspGeneralSerializationProcessor;
import io.andreygs.jcsp.base.processing.buffer.internal.ICspSerializationBuffer;
import io.andreygs.jcsp.base.processing.state.internal.ICspCommonProcessingState;
import io.andreygs.jcsp.base.processing.typetraits.annotations.CspAsReference;
import io.andreygs.jcsp.base.processing.typetraits.annotations.CspProcessorAutoGeneratable;
import io.andreygs.jcsp.base.processing.ICspDataSerializationProcessor;
import io.andreygs.jcsp.base.processing.typetraits.annotations.CspSerializable;
import io.andreygs.jcsp.base.processing.typetraits.annotations.CspFixedSizeArray;
import io.andreygs.jcsp.base.types.CspRuntimeException;
import io.andreygs.jcsp.base.types.CspStatus;

import java.lang.reflect.Field;
import java.lang.reflect.GenericArrayType;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

/**
 *
 */
public class CspAutoGeneratedSerializationProcessorFactory
{
    public static ICspDataSerializationProcessor createAutoGeneratedSerializationProcessor(Class<?> serializingClass)
        throws CspRuntimeException
    {
        if (!isAutoGeneratable(serializingClass))
        {
            throw CspRuntimeException.createCspRuntimeException(CspStatus.NO_SUCH_HANDLER,
                serializingClass.getName() + " is not annotated with " + CspProcessorAutoGeneratable.class.getName(),
                null);
        }

        List<ICspDataSerializationProcessor> callbacks = new ArrayList<ICspDataSerializationProcessor>();

        return new AutoGeneratedDataSerializationProcessor(serializingClass, callbacks);
    }

    private static boolean isAutoGeneratable(Class<?> clazz)
    {
        return clazz.isAnnotationPresent(CspProcessorAutoGeneratable.class);
    }

    private static void produceCallbacks(List<ICspDataSerializationProcessor> callbacks, Class<?> clazz)
    {
        Class<?> parentClazz = clazz.getSuperclass();
        if (isAutoGeneratable(parentClazz))
        {
            callbacks.add((value, state) -> ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor().serialize(value, parentClazz, state));
        }

        Arrays.stream(clazz.getDeclaredFields()).forEach(field -> field.setAccessible(true));

        Arrays.stream(clazz.getDeclaredFields())
            .filter(field -> field.getAnnotation(CspSerializable.class) != null)
            .sorted(Comparator.comparingInt(field -> field.getAnnotation(CspSerializable.class).order()))
            .forEach(field -> produceFieldSerializationCallbacks(callbacks, field));
    }

    private static void produceFieldSerializationCallbacks(List<ICspDataSerializationProcessor> callbacks, Field field)
    {
        Class<?> clazz = field.getType();

        if (clazz == boolean.class)
        {
            callbacks.add((value, state) -> {
                try
                {
                    ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor().serialize(field.getBoolean(value), state);
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }
        else if (clazz == byte.class)
        {
            callbacks.add((value, state) -> {
                try
                {
                    ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor().serializeByte(field.getByte(value), state);
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }
        else if (clazz == short.class)
        {
            callbacks.add((value, state) -> {
                try
                {
                    ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor().serializeShort(field.getShort(value), state);
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }
        else if (clazz == int.class)
        {
            callbacks.add((value, state) -> {
                try
                {
                    ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor().serializeInt(field.getInt(value), state);
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }
        else if (clazz == long.class)
        {
            callbacks.add((value, state) -> {
                try
                {
                    ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor().serializeLong(field.getLong(value), state);
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }
        else if (clazz == char.class)
        {
            callbacks.add((value, state) -> {
                try
                {
                    ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor().serializeChar(field.getChar(value), state);
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }
        else if (clazz == float.class)
        {
            callbacks.add((value, state) -> {
                try
                {
                    ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor().serializeFloat(field.getFloat(value), state);
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }
        else if (clazz == double.class)
        {
            callbacks.add((value, state) -> {
                try
                {
                    ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor().serializeDouble(field.getDouble(value), state);
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            });
        }

        boolean asReference = field.getAnnotation(CspAsReference.class) != null;

        if (clazz.isArray())
        {
            boolean fixedSizeArray = field.getAnnotation(CspFixedSizeArray.class) != null;

            if (clazz == boolean[].class)
            {
                callbacks.add((value, state) -> {
                    try
                    {
                        ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor()
                               .serialize((boolean[]) field.get(value), asReference, fixedSizeArray, state);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else if (clazz == byte[].class)
            {
                callbacks.add((value, state) -> {
                    try
                    {
                        ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor()
                               .serialize((byte[]) field.get(value), asReference, fixedSizeArray, state);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else if (clazz == short[].class)
            {
                callbacks.add((value, state) -> {
                    try
                    {
                        ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor()
                               .serialize((short[]) field.get(value), asReference, fixedSizeArray, state);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else if (clazz == int[].class)
            {
                callbacks.add((value, state) -> {
                    try
                    {
                        ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor()
                               .serialize((int[]) field.get(value), asReference, fixedSizeArray, state);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else if (clazz == long[].class)
            {
                callbacks.add((value, state) -> {
                    try
                    {
                        ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor()
                               .serialize((long[]) field.get(value), asReference, fixedSizeArray, state);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else if (clazz == char[].class)
            {
                callbacks.add((value, state) -> {
                    try
                    {
                        ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor()
                               .serialize((char[]) field.get(value), asReference, fixedSizeArray, state);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else if (clazz == float[].class)
            {
                callbacks.add((value, state) -> {
                    try
                    {
                        ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor()
                               .serialize((float[]) field.get(value), asReference, fixedSizeArray, state);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else if (clazz == double[].class)
            {
                callbacks.add((value, state) -> {
                    try
                    {
                        ((ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer>)state).getCspGeneralProcessor()
                               .serialize((double[]) field.get(value), asReference, fixedSizeArray, state);
                    }
                    catch (IllegalAccessException e)
                    {
                        throw new RuntimeException(e);
                    }
                });
            }
            else
            {
                Type type = field.getGenericType();
                if (type instanceof GenericArrayType arrayType)
                {

                }
/*
                    int elementsCount = Array.getLength(value);
                Class<?> elementsClazz = fieldClazz.getComponentType();

                if (ICspVersionable.class.isAssignableFrom(fieldClazz.getComponentType()))
                {
                    for (int i = 0; i < elementsCount; ++i)
                    {
                        Object element = Array.get(value, i);
                       // serialize((ICspVersionable) element, elementsClazz, state);
                    }
                }
                else
                {
                    for (int i = 0; i < elementsCount; ++i)
                    {
                        Object element = Array.get(value, i);
                       // serialize(element, state);
                    }
                }*/
            }
        }
        else
        {
            //serialize(field.get(value), state);
        }
    }

    private static class AutoGeneratedDataSerializationProcessor
        implements ICspDataSerializationProcessor
    {
        private final Class<?> clazz;
        private final List<ICspDataSerializationProcessor> callbacks;

        public AutoGeneratedDataSerializationProcessor(Class<?> clazz, List<ICspDataSerializationProcessor> callbacks)
        {
            this.clazz = clazz;
            this.callbacks = callbacks;
        }

        @Override
        public void serialize(Object value, Object state)
        {
            callbacks.forEach(callback -> callback.serialize(value, state));
        }

        private ICspDataSerializationProcessor getP(Field field, Object value, ICspCommonProcessingState<ICspGeneralSerializationProcessor, ICspSerializationBuffer> context)
        {
            ICspDataSerializationProcessor processor = (valueX, stateX) -> {
                try
                {
                    context.getCspGeneralProcessor().serializeInt(field.getInt(valueX), stateX);
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            };
            return processor;
        }
    }
}
