/**
 * @author Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * License
 * <p>
 * Copyright 2025 Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files
 * (the "Software"), to deal in the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so,
 * subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of
 * the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package io.andreygs.jcsp.base.processing.internal;

import io.andreygs.jcsp.base.processing.ICspDataGeneralSerializationProcessor;
import io.andreygs.jcsp.base.processing.ICspDataSerializationProcessor;
import io.andreygs.jcsp.base.processing.proxy.internal.ICspDataProxyProcessorFactory;
import io.andreygs.jcsp.base.processing.proxy.internal.ICspDataSerializationProxyProcessor;

import java.lang.reflect.Field;
import java.util.List;

/**
 * TODO: place description here
 */
final class CspDataSerializationProcessorGenerator
    extends AbstractCspDataProcessorGenerator<ICspDataSerializationProcessor<?>, ICspDataSerializationProxyProcessor<?>>
{
    private final ICspDataProxyProcessorFactory<ICspDataSerializationProxyProcessor<?>> proxyProcessorFactory;

    CspDataSerializationProcessorGenerator(
        ICspDataProxyProcessorFactory<ICspDataSerializationProxyProcessor<?>> proxyProcessorFactory)
    {
        this.proxyProcessorFactory = proxyProcessorFactory;
    }

    @Override
    protected void addParentClass(Class<?> parentClazz, List<ICspDataSerializationProxyProcessor<?>> proxyProcessors)
    {
         proxyProcessors.add(
             (value, generalProcessor) -> generalProcessor.serialize(value, false, parentClazz));
    }

    @Override
    protected void addField(Field field, List<ICspDataSerializationProxyProcessor<?>> proxyProcessors)
    {
        // TODO
    }

    @Override
    protected ICspDataSerializationProcessor<?> createProcessor(
        List<ICspDataSerializationProxyProcessor<?>> proxyProcessors)
    {
        return new AutoGeneratedDataSerializationProcessor<Object>(proxyProcessors);
    }

    private static class AutoGeneratedDataSerializationProcessor<T>
        implements ICspDataSerializationProcessor<T>
    {
        private final List<ICspDataSerializationProxyProcessor<T>> proxyProcessors;

        public AutoGeneratedDataSerializationProcessor(List<ICspDataSerializationProxyProcessor<?>> proxyProcessors)
        {
            @SuppressWarnings("unchecked")
            List<ICspDataSerializationProxyProcessor<T>> proxyProcessorsLocal =
                (List<ICspDataSerializationProxyProcessor<T>>)(List<?>)proxyProcessors;
            this.proxyProcessors = List.copyOf(proxyProcessorsLocal);
        }

        @Override
        public void serialize(T value, ICspDataGeneralSerializationProcessor generalProcessor)
        {
            if (generalProcessor instanceof ICspDataExtendedGeneralSerializationProcessor extendedGeneralProcessor)
            {
                for (ICspDataSerializationProxyProcessor<T> proxyProcessor : proxyProcessors)
                {
                    proxyProcessor.serialize(value, extendedGeneralProcessor);
                }
            }
            else
            {
                throw new IllegalArgumentException(
                    Messages.ICspDataGeneralSerializationProcessor_instance_is_not_extended);
            }
        }
    }
}
