/**
 * @author Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * License
 * <p>
 * Copyright 2025 Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files
 * (the "Software"), to deal in the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so,
 * subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of
 * the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package io.andreygs.jcsp.base.processing.internal;

import io.andreygs.jcsp.base.processing.ICspDataSerializationProcessor;
import io.andreygs.jcsp.base.processing.session.ICspDataSerializationSession;
import io.andreygs.jcsp.base.processing.typetraits.annotations.CspProcessorAutoGeneratable;
import io.andreygs.jcsp.base.types.CspRuntimeException;
import io.andreygs.jcsp.base.types.CspStatus;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

/**
 * TODO: place description here
 */
public class CspDataProcessorGenerator<T>
    implements ICspDataProcessorGenerator<T>
{
    private final List<T> callbacks = new ArrayList<>();

    @Override
    public T generateDataProcessor(Class<?> structClazz) throws CspRuntimeException
    {
        if (!isAutoGeneratable(structClazz))
        {
            throw CspRuntimeException.createCspRuntimeException(CspStatus.NO_SUCH_HANDLER,
                                                                structClazz.getName() + " is not annotated with " + CspProcessorAutoGeneratable.class.getName(), null);
        }
        return new AutoGeneratedDataSerializationProcessor<T>(structClazz, callbacks);
    }

    private static boolean isAutoGeneratable(Class<?> clazz)
    {
        return clazz.isAnnotationPresent(CspProcessorAutoGeneratable.class);
    }

    private static class AutoGeneratedDataSerializationProcessor<T>
        implements ICspDataSerializationProcessor
    {
        private final Class<?> clazz;
        private final List<T> callbacks;

        public AutoGeneratedDataSerializationProcessor(Class<?> clazz, List<T> callbacks)
        {
            this.clazz = clazz;
            this.callbacks = callbacks;
        }

        @Override
        public void serialize(Object value, ICspDataSerializationSession session)
        {
            callbacks.forEach(callback -> callback.serialize(value, session));
        }

        private ICspDataSerializationProcessor getP(Field field, Object value, ICspDataSerializationSession session)
        {
            ICspDataSerializationProcessor processor = (valueX, stateX) -> {
                try
                {
                    session.getCspDataGeneralProcessor().serializeInt(field.getInt(valueX), stateX);
                }
                catch (IllegalAccessException e)
                {
                    throw new RuntimeException(e);
                }
            };
            return processor;
        }
    }
}
