/**
 * @author Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * License
 * <p>
 * Copyright 2025 Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files
 * (the "Software"), to deal in the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so,
 * subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of
 * the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package io.andreygs.jcsp.base.processing.internal;

import io.andreygs.jcsp.base.processing.ICspDataDeserializationProcessor;
import io.andreygs.jcsp.base.processing.ICspDataGeneralDeserializationProcessor;
import io.andreygs.jcsp.base.processing.ICspDataGeneralSerializationProcessor;
import io.andreygs.jcsp.base.processing.ICspDataSerializationProcessor;
import io.andreygs.jcsp.base.processing.annotations.CspProcessorAutoGeneratable;

import java.lang.reflect.AnnotatedType;
import java.util.List;
import java.util.Optional;

/**
 * Registry of CSP serialization/deserialization processors for specific classes.
 * <p>
 * Registering of processor is always necessary when target class not annotated with
 * {@link CspProcessorAutoGeneratable} interface (because they are generating automatically) and not
 * instance of types supported by {@link ICspDataGeneralSerializationProcessor} and
 * {@link ICspDataGeneralDeserializationProcessor} processors. These (supported) include:
 * <ul>
 *     <li>any primitive: boolean, byte, short, int, long, char, float, double</li>
 *     <li>{@link String}</li>
 *     <li>{@link java.util.Collection}, {@link java.util.Map}. Note, that if class is implementing one of this
 *     it will be serialized as collection or map (first check is for collection, second for map). However, one can
 *     override this behavior by registering its own processors for any inheritors of these including other
 *     interfaces like {@link java.util.List}, but if there is no very good reason, this should be avoided.</li>
 *     <li>arrays</li>
 * </ul>
 * <p>
 * One can override autogenerated {@link CspProcessorAutoGeneratable} subtypes processors by registering its own.
 * This approach can be handy if it will somehow speed up serialization process or add some asserts of deserialized
 * (or maybe even serialized) data.
 * <p>
 * The strategy of registries number in application is not strictly defined.
 * There can be a one (or two, for both - serialization and deserialization) or several units,
 * each one for different CSP Interfaces (or modules) or/and if there are different policies
 * for work with different sources/targets of CSP interactions.
 * <p>
 * Please note that one-dimensional arrays of any type must not have separate processors.
 * <p>
 * Thread-safe.
 *
 * @param <P> one of {@link ICspDataSerializationProcessor} or {@link ICspDataDeserializationProcessor},
 *           depending on what kind of registry is.
 */
public interface ICspDataProcessorRegistry<P>
{
    /**
     * Registers processor for ordinary and generic (non-primitive, non-array) type for later use.
     * <p>
     * If class processor already have been registered, then new processor will override previous registration.
     * But if you want to have both processors - by one for different cases, for example -
     * you should create new registry, fill it with all necessary processors including current one
     * and use different registries in requisite scenarios.
     *
     * @param clazz Class that processor should handle.
     * @param processor Processor that will be used in serialization or deserialization process.
     */
    void registerProcessor(Class<?> clazz, P processor);

    /**
     * Registers processor for composite type for later use.
     * <p>
     * If class processor already have been registered, then new processor will override previous registration.
     * But if you want to have both processors - by one for different cases, for example -
     * you should create new registry, fill it with all necessary processors including current one
     * and use different registries in requisite scenarios.
     *
     * @param compositeType Type which has non-trivial traits, like generic parameters and nested structure.
     *                      For example: List&ltMap&lt@CspReference String, Integer[]>
     * @param processor Processor that will be used in serialization or deserialization process.
     */
    void registerProcessor(AnnotatedType compositeType, P processor);

    /**
     * Finds already registered processor for chosen ordinary (non-primitive, non-generic, non-array) class.
     *
     * @param clazz Class which processor need to be found.
     * @return optional processor.
     */
    Optional<P> findOrdinaryProcessor(Class<?> clazz);

    /**
     * Finds already registered processor for chosen generic class.
     *
     * @param clazz Class for which you need to find the processor holder and its parameters.
     * @return optional holder for class and its parameters.
     */
    Optional<IGenericProcessorHolder<P>> findGenericProcessor(Class<?> clazz);

    /**
     * Finds already registered processor for chosen composite type.
     *
     * @param compositeType Type which processor need to be found.
     * @return optional processor.
     */
    Optional<P> findGenericProcessor(AnnotatedType compositeType);

    void unregisterAllProcessors();

    public interface IGenericProcessorHolder<P>
    {
        P getProcessor();

        List<String> getTypeVariableNames();
    }
}
