/**
 * @author Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * License
 * <p>
 * Copyright 2025 Andrey Grabov-Smetankin <ukbpyh@gmail.com>
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files
 * (the "Software"), to deal in the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so,
 * subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of
 * the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package io.andreygs.jcsp.internal.processing.data;

import io.andreygs.jcsp.api.processing.data.ICspSerializationProcessor;
import io.andreygs.jcsp.api.processing.data.clazz.ICspClassSerializationProcessor;
import io.andreygs.jcsp.internal.processing.data.type.factory.ICspTypeProcessorFactory;
import io.andreygs.jcsp.internal.processing.data.type.ICspTypeSerializationProcessor;

import java.lang.reflect.Field;
import java.util.List;

/**
 * TODO: place description here
 */
public final class CspClassSerializationProcessorGenerator
    extends AbstractCspClassProcessorGenerator<ICspClassSerializationProcessor<?>, ICspTypeSerializationProcessor>
{
    private final ICspTypeProcessorFactory<ICspTypeSerializationProcessor> proxyProcessorFactory;

    public CspClassSerializationProcessorGenerator(
        ICspTypeProcessorFactory<ICspTypeSerializationProcessor> proxyProcessorFactory)
    {
        this.proxyProcessorFactory = proxyProcessorFactory;
    }

    @Override
    protected void addParentClass(Class<?> parentClazz, List<ICspTypeSerializationProcessor> typeProcessors)
    {
        // TODO need additional method for generic parent class
        typeProcessors.add(
             (value, processor) -> processor.serialize(value, false, parentClazz));
    }

    @Override
    protected void addField(Field field, List<ICspTypeSerializationProcessor> typeProcessors)
    {
        // TODO
    }

    @Override
    protected ICspClassSerializationProcessor<?> createProcessor(List<ICspTypeSerializationProcessor> typeProcessors)
    {
        return new AutoGeneratedClassSerializationProcessor<Object>(typeProcessors);
    }

    private static class AutoGeneratedClassSerializationProcessor<T>
        implements ICspClassSerializationProcessor<T>
    {
        private final List<ICspTypeSerializationProcessor> typeProcessors;

        public AutoGeneratedClassSerializationProcessor(List<ICspTypeSerializationProcessor> typeProcessors)
        {
            this.typeProcessors = List.copyOf(typeProcessors);
        }

        @Override
        public void serialize(T value, ICspSerializationProcessor processor)
        {
            if (processor instanceof ICspExtendedSerializationProcessor extendedProcessor)
            {
                for (ICspTypeSerializationProcessor typeProcessor : typeProcessors)
                {
                    typeProcessor.serialize(value, extendedProcessor);
                }
            }
            else
            {
                throw new IllegalArgumentException(
                    Messages.CspClassSerializationProcessorGenerator_ICspSerializationProcessor_is_invalid);
            }
        }
    }
}
